Frontend/EgeApp.Frontend.Mvc/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using EgeApp.Frontend.Mvc.Models.Category;
using EgeApp.Frontend.Mvc.Services;

namespace EgeApp.Frontend.Mvc.Controllers
{
    public class CategoryController : Controller
    {
        public async Task<IActionResult> Index()
        {
            var response = await CategoryService.GetActives();
            if (!response.IsSucceeded)
            {
                TempData["Error"] = response.Error;
                return RedirectToAction("Error", "Home");
            }
            return View(response.Data);
        }

        public IActionResult Create()
        {
            return View(new CategoryCreateViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> Create(CategoryCreateViewModel model)
        {
            if (!ModelState.IsValid) return View(model);

            var response = await CategoryService.CreateAsync(model);
            if (!response.IsSucceeded)
            {
                ModelState.AddModelError("", response.Error);
                return View(model);
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Edit(int id)
        {
            var response = await CategoryService.GetByIdAsync(id);
            if (!response.IsSucceeded)
            {
                TempData["Error"] = response.Error;
                return RedirectToAction("Error", "Home");
            }
            return View(response.Data);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(CategoryUpdateViewModel model)
        {
            if (!ModelState.IsValid) return View(model);

            var response = await CategoryService.UpdateAsync(model);
            if (!response.IsSucceeded)
            {
                ModelState.AddModelError("", response.Error);
                return View(model);
            }
            return RedirectToAction("Index");
        }

        // GET: Delete Confirmation Page
        public async Task<IActionResult> Delete(int id)
        {
            var response = await CategoryService.GetByIdAsync(id);
            if (!response.IsSucceeded)
            {
                TempData["Error"] = response.Error;
                return RedirectToAction("Error", "Home");
            }
            return View(response.Data); // Kategori bilgilerini silme onayı için görüntüle
        }

        // POST: Delete Action
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> ConfirmDelete(int id)
        {
            var response = await CategoryService.DeleteAsync(id);
            if (!response.IsSucceeded)
            {
                TempData["Error"] = response.Error;
                return RedirectToAction("Error", "Home");
            }
            return RedirectToAction("Index");
        }

    }
}

Frontend/EgeApp.Frontend.Mvc/Controllers/OrderController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using EgeApp.Frontend.Mvc.Data.Entities;
using EgeApp.Frontend.Mvc.Models.Order;
using EgeApp.Frontend.Mvc.Services;
using EgeApp.Frontend.Mvc.Models.Cart;
using EgeApp.Backend.Shared.Dtos.CartDtos;

namespace EgeApp.Frontend.Mvc.Controllers
{
    public class OrderController : Controller
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly INotyfService _notyfService;

        public OrderController(UserManager<AppUser> userManager, INotyfService notyfService)
        {
            _userManager = userManager;
            _notyfService = notyfService;
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Checkout()
        {
            var user = await _userManager.FindByNameAsync(User.Identity.Name);
            var userId = await _userManager.GetUserIdAsync(user);
            var cartResult = await CartService.GetCartAsync(userId);

            if (!cartResult.IsSucceeded)
            {
                return RedirectToAction("Error", "Home");
            }

            var cartViewModel = MapToViewModel(cartResult.Data);

            OrderCreateViewModel model = new()
            {
                Cart = cartViewModel,
                FirstName = "Sezen",
                LastName = "Aksu",
                Address = "Düpedüz Sk. Yamuk yumuk ap. D:12 Beşiktaş",
                City = "İstanbul",
                Email = "sezenaksu@gmail.com",
                PhoneNumber = "5557778844",
                PaymentType = 0,
                UserId = userId
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Checkout(OrderCreateViewModel model)
        {
            var user = await _userManager.FindByNameAsync(User.Identity.Name);
            var userId = await _userManager.GetUserIdAsync(user);
            var cartResult = await CartService.GetCartAsync(userId);

            if (!cartResult.IsSucceeded)
            {
                return RedirectToAction("Error", "Home");
            }

            // DTO'dan ViewModel'e dönüşüm
            var cartViewModel = MapToViewModel(cartResult.Data);

            List<OrderItemViewModel> orderItems = new();
            foreach (var cartItem in cartResult.Data.CartItems)
            {
                orderItems.Add(new OrderItemViewModel
                {
                    ProductId = cartItem.ProductId,
                    Price = cartItem.Price,
                    Quantity = cartItem.Quantity
                });
            }

            model.OrderItems = orderItems;
            model.UserId = userId;

            var result = await OrderService.AddOrderAsync(model);
            if (!result.IsSucceeded)
            {
                _notyfService.Error(result.Error);
                return View(model);
            }

            await CartService.ClearCartAsync(cartResult.Data.Id);
            _notyfService.Success("Ödeme işlemi başarıyla tamamlandı!");
            _notyfService.Information("Siparişiniz alındı!");
            return RedirectToAction("Index", "Home");
        }

        private CartViewModel MapToViewModel(CartDto cartDto)
        {
            if (cartDto == null) return new CartViewModel();

            return new CartViewModel
            {
                Id = cartDto.Id,
                CreatedDate = cartDto.CreatedDate,
                UserId = cartDto.UserId,
                CartItems = cartDto.CartItems.Select(item => new CartItemViewModel
                {
                    Id = item.ProductId,
                    ProductId = item.ProductId,
                    ProductName = item.ProductName,
                    ImageUrl = item.ImageUrl,
                    Price = item.Price,
                    Quantity = item.Quantity,
                    CartId = cartDto.Id
                }).ToList()
            };
        }
    }
}

Frontend/EgeApp.Frontend.Mvc/Controllers/ProductController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using EgeApp.Frontend.Mvc.Data.Entities;
using EgeApp.Frontend.Mvc.Services;
using EgeApp.Frontend.Mvc.Models.Product;

namespace EgeApp.Frontend.Mvc.Controllers
{

    public class ProductController : Controller
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly INotyfService _notyfService;

        public ProductController(INotyfService notyfService, UserManager<AppUser> userManager)
        {
            _notyfService = notyfService;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var result = await ProductService.GetAllAsync();
            if (!result.IsSucceeded)
            {
                TempData["Error"] = result.Error ?? "Ürünler yüklenirken bir hata oluştu.";
                return RedirectToAction("Error", "Home");
            }

            return View(result.Data);
        }
        public IActionResult Shop()
        {
            return View(); 
        }
        public async Task<IActionResult> Details(int id)
        {
            var result = await ProductService.GetByIdAsync(id);

            if (!result.IsSucceeded)
            {
                _notyfService.Error("Ürün detayları yüklenemedi.");
                return RedirectToAction("Index");
            }

            if (User.Identity.IsAuthenticated)
            {
                var user = await _userManager.FindByNameAsync(User.Identity.Name);
                var cartResult = await CartService.GetCartAsync(user.Id);

                if (!cartResult.IsSucceeded)
                {
                    _notyfService.Error("Sepet bilgileri alınırken bir hata oluştu.");
                    return RedirectToAction("Index");
                }

                ViewBag.CountOfItems = cartResult.Data.CountOfItem;
            }

            return View(result.Data);
        }
        [HttpGet("GetDiscountedProducts")]
        public async Task<IActionResult> GetDiscountedProducts()
        {
            // Asenkron sonucu bekle
            var discountedProducts = await ProductService.GetDiscountedProductsAsync();

            // Hata kontrolü
            if (discountedProducts == null || !discountedProducts.IsSucceeded || discountedProducts.Data == null || !discountedProducts.Data.Any())
            {
                return NotFound("No discounted products found.");
            }

            // Başarılı sonuç döndür
            return Ok(discountedProducts.Data);
        }

        public async Task<IActionResult> ProductList()
        {
            var response = await ProductService.GetAllAsync();

            // Eğer response başarılıysa ve ürünler varsa işlemleri gerçekleştir
            if (response != null && response.Data != null)
            {
                var products = response.Data
                    .Select(p => new ProductListViewModel
                    {
                        Id = p.Id,
                        Name = p.Name,
                        ImageUrl = p.ImageUrl,
                        Price = p.Price,
                        DiscountedPrice = p.DiscountedPrice,
                        IsActive = p.IsActive,
                        IsFreeShipping = p.IsFreeShipping
                    }).ToList();

                return View(products);
            }

            // Eğer veri yoksa veya hata varsa, hata sayfasına yönlendirin veya uygun bir yanıt döndürün
            return View(new List<ProductListViewModel>());
        }


    }
}

Frontend/EgeApp.Frontend.Mvc/Areas/Admin/Views/Shared/_AdminLayout.cshtml
@using EgeApp.Frontend.Mvc.Models.Other
<!DOCTYPE html>
<html lang="tr">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Ege Medikal Admin</title>
    @await Html.PartialAsync("_StylesPartial")
    @await RenderSectionAsync("Styles", false)
</head>

<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">
        @await Html.PartialAsync("_PreloaderPartial")
        @await Html.PartialAsync("_NavbarPartial")
        @await Html.PartialAsync("_MainSidebarPartial")

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            @{
                var contentDataModel = new ContentDataModel
            {
                PageHeader = ViewData["PageHeader"]?.ToString() ?? "Default Header", // Null kontrolü ekledim
                ShowButton = ViewData["ShowButton"] != null && (bool)ViewData["ShowButton"], // ShowButton için null
               
            ButtonTitle = ViewData["ButtonTitle"]?.ToString() ?? "Default Button", // Null kontrolü ekledim
                ButtonLink = ViewData["ButtonLink"]?.ToString() ?? "#" // Null kontrolü ekledim
            };
            }
            @await Html.PartialAsync("_ContentHeaderPartial", contentDataModel)

            <!-- Main content -->
            <section class="content">
                <div class="container-fluid">
                    @RenderBody()
                </div><!-- /.container-fluid -->
            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->


        @await Html.PartialAsync("_FooterPartial")
    </div>
    <!-- ./wrapper -->
    @await Html.PartialAsync("_ScriptsPartial")
    @await Component.InvokeAsync("Notyf")
    @await RenderSectionAsync("Scripts", false)
</body>

</html>

Frontend/EgeApp.Frontend.Mvc/Areas/Admin/Views/Shared/_ContentHeaderPartial.cshtml
@model EgeApp.Frontend.Mvc.Models.Other.ContentDataModel

<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">@Model.PageHeader</h1>
            </div><!-- /.col -->
            <div class="col-sm-6 text-right">
                @if (Model.ShowButton)
                {
                    <a href="@Model.ButtonLink" class="btn btn-primary">@Model.ButtonTitle</a>
                }
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

Frontend/EgeApp.Frontend.Mvc/Areas/Admin/Views/Shared/_DataTablesPartial.cshtml
<script>
    $(function () {

        $("#my-data-table").DataTable({
            "responsive": true,
            "lengthChange": true,
            "lengthMenu": [10, 20, 50, 100],
            "autoWidth": true
        });
    });
</script>

Frontend/EgeApp.Frontend.Mvc/Areas/Admin/Views/Shared/_FooterPartial.cshtml
<footer class="main-footer">
    @* <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
        <b>Version</b> 3.2.0 *@
    </div>
</footer>

Frontend/EgeApp.Frontend.Mvc/Areas/Admin/Views/Shared/_MainSidebarPartial.cshtml
<!-- SOL MENÜ -->
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="/admin" class="brand-link">
        <img src="~/admin/dist/img/logoicon.svg" alt="ege-logo" class="brand-image img-circle elevation-3"
            style="opacity: .8">
        <span class="brand-text font-weight-light">Ege Medikal Admin</span>
    </a>
    <a href="/" target="_blank" class="brand-link">
        <img src="~/admin/dist/img/logoname.svg" alt="ege-logo" class="brand-image img-circle elevation-3"
            style="opacity: .8">
        <span class="brand-text font-weight-light">Uygulamaya Geç </span>
    </a>
    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="~/admin/dist/img/muhammedtopcu.jpg" class="img-circle elevation-2" alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block">@User.Identity.Name</a>
            </div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Kategoriler -->
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-list-alt"></i> <!-- Kategori simgesi -->
                        <p>
                            Kategoriler
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a asp-area="Admin" asp-controller="Category" asp-action="Index" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Kategori Listesi</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="Admin" asp-controller="Category" asp-action="Create" class="nav-link">
                                <i class="far fa-plus-square nav-icon"></i> <!-- Kategori ekleme simgesi -->
                                <p>Kategori Ekle</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <!-- Ürünler -->
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-cogs"></i> <!-- Ürün yönetimi simgesi -->
                        <p>
                            Ürünler
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a asp-area="Admin" asp-controller="Product" asp-action="Index" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Ürün Listesi</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="Admin" asp-controller="Product" asp-action="Create" class="nav-link">
                                <i class="far fa-plus-circle nav-icon"></i> <!-- Ürün ekleme simgesi -->
                                <p>Ürün Ekle</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <!-- Siparişler -->
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-box"></i> <!-- Sipariş simgesi -->
                        <p>
                            Siparişler
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a asp-area="Admin" asp-controller="Order" asp-action="Index" asp-route-id=""
                                class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Tüm Siparişler</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="Admin" asp-controller="Order" asp-action="Index" asp-route-id="0"
                                class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Yeni Siparişler</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <!-- Kullanıcılar -->
                <li class="nav-item">
                    <a asp-area="Admin" asp-controller="User" asp-action="Index" class="nav-link">
                        <i class="nav-icon fas fa-users"></i> <!-- Kullanıcı simgesi -->
                        <p>
                            Kullanıcılar
                        </p>
                    </a>
                </li>
                <!-- Roller -->
                <li class="nav-item">
                    <a asp-area="Admin" asp-controller="Role" asp-action="Index" class="nav-link">
                        <i class="nav-icon fas fa-user-shield"></i> <!-- Roller simgesi -->
                        <p>
                            Roller
                        </p>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>

Frontend/EgeApp.Frontend.Mvc/Areas/Admin/Views/Shared/_NavbarPartial.cshtml
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <!-- Navbar Search -->
        <li class="nav-item">
            <a class="nav-link" data-widget="navbar-search" href="#" role="button">
                <i class="fas fa-search"></i>
            </a>
            <div class="navbar-search-block">
                <form class="form-inline">
                    <div class="input-group input-group-sm">
                        <input class="form-control form-control-navbar" type="search" placeholder="Arama"
                            aria-label="Search">
                        <div class="input-group-append">
                            <button class="btn btn-navbar" type="submit">
                                <i class="fas fa-search"></i>
                            </button>
                            <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                                <i class="fas fa-times"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </li>

        <li class="nav-item">
            <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                <i class="fas fa-expand-arrows-alt"></i>
            </a>
        </li>
    </ul>
</nav>
<!-- /.navbar -->

Frontend/EgeApp.Frontend.Mvc/Areas/Admin/Views/Shared/_PreloaderPartial.cshtml
<!-- Preloader -->
<div class="preloader flex-column justify-content-center align-items-center">
    <img class="animation__shake" src="~/admin/dist/img/logoicon.svg" alt="MSCD-5 Sınıfı" height="60" width="60">
</div>

Frontend/EgeApp.Frontend.Mvc/Areas/Admin/Views/Shared/_ScriptsPartial.cshtml
<!-- jQuery -->
<script src="~/admin/plugins/jquery/jquery.min.js"></script>
<!-- jQuery UI 1.11.4 -->
<script src="/admin/plugins/jquery-ui/jquery-ui.min.js"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
    $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="~/admin/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>

<!-- overlayScrollbars -->
<script src="~/admin/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>

<!-- AdminLTE App -->
<script src="~/admin/dist/js/adminlte.js"></script>

Frontend/EgeApp.Frontend.Mvc/Areas/Admin/Views/Shared/_StylesPartial.cshtml
<!-- Google Font: Source Sans Pro -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
<!-- Font Awesome -->
<link rel="stylesheet" href="~/admin/plugins/fontawesome-free/css/all.min.css">
<!-- Ionicons -->
<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
<!-- Tempusdominus Bootstrap 4 -->
<link rel="stylesheet" href="~/admin/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
<!-- iCheck -->
<link rel="stylesheet" href="~/admin/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
<!-- JQVMap -->
<link rel="stylesheet" href="~/admin/plugins/jqvmap/jqvmap.min.css">
<!-- Theme style -->
<link rel="stylesheet" href="~/admin/dist/css/adminlte.min.css">
<!-- overlayScrollbars -->
<link rel="stylesheet" href="~/admin/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
<!-- Daterange picker -->
<link rel="stylesheet" href="~/admin/plugins/daterangepicker/daterangepicker.css">
<!-- summernote -->
<link rel="stylesheet" href="~/admin/plugins/summernote/summernote-bs4.min.css">